chn_dict = {"0":"unknown",
             "1":"general",
             "2":"stress",
             "3":"strain",
             "5":"temperature",
             "6":"heat flux",
             "8":"displacement",
             "9":"reaction force",
             "11":"velocity2,
             "12":"acceleration",
             "13":"excitation force",
             "15":"pressure",
             "16":"mass",
             "17":"time",
             "18":"frequency",
             "19":"rpm",
             "20":"order",
             "21":"sound pressure",
             "22":"sound intensity",
             "23":"sound power",}