# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1024, 768)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.addFilesButton = QtWidgets.QPushButton(Dialog)
        self.addFilesButton.setObjectName("addFilesButton")
        self.horizontalLayout.addWidget(self.addFilesButton)
        self.addFolderButton = QtWidgets.QPushButton(Dialog)
        self.addFolderButton.setObjectName("addFolderButton")
        self.horizontalLayout.addWidget(self.addFolderButton)
        self.removeFromInputButton = QtWidgets.QPushButton(Dialog)
        self.removeFromInputButton.setObjectName("removeFromInputButton")
        self.horizontalLayout.addWidget(self.removeFromInputButton)
        self.addToOutputButton = QtWidgets.QPushButton(Dialog)
        self.addToOutputButton.setObjectName("addToOutputButton")
        self.horizontalLayout.addWidget(self.addToOutputButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.inputLabel = QtWidgets.QLabel(Dialog)
        self.inputLabel.setObjectName("inputLabel")
        self.verticalLayout.addWidget(self.inputLabel)
        self.inputFilterEdit = QtWidgets.QLineEdit(Dialog)
        self.inputFilterEdit.setObjectName("inputFilterEdit")
        self.verticalLayout.addWidget(self.inputFilterEdit)
        self.inputListView = QtWidgets.QListView(Dialog)
        self.inputListView.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.inputListView.setObjectName("inputListView")
        self.verticalLayout.addWidget(self.inputListView)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.sameSettingsCheckBox = QtWidgets.QCheckBox(Dialog)
        self.sameSettingsCheckBox.setObjectName("sameSettingsCheckBox")
        self.verticalLayout_2.addWidget(self.sameSettingsCheckBox)
        self.channelsMappingLabel = QtWidgets.QLabel(Dialog)
        self.channelsMappingLabel.setObjectName("channelsMappingLabel")
        self.verticalLayout_2.addWidget(self.channelsMappingLabel)
        self.channelsTreeView = QtWidgets.QTreeView(Dialog)
        self.channelsTreeView.setObjectName("channelsTreeView")
        self.verticalLayout_2.addWidget(self.channelsTreeView)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.setOutputFolderButton = QtWidgets.QPushButton(Dialog)
        self.setOutputFolderButton.setObjectName("setOutputFolderButton")
        self.horizontalLayout_2.addWidget(self.setOutputFolderButton)
        self.convertButton = QtWidgets.QPushButton(Dialog)
        self.convertButton.setObjectName("convertButton")
        self.horizontalLayout_2.addWidget(self.convertButton)
        self.removeFromOutputButton = QtWidgets.QPushButton(Dialog)
        self.removeFromOutputButton.setObjectName("removeFromOutputButton")
        self.horizontalLayout_2.addWidget(self.removeFromOutputButton)
        self.backToInputButton = QtWidgets.QPushButton(Dialog)
        self.backToInputButton.setObjectName("backToInputButton")
        self.horizontalLayout_2.addWidget(self.backToInputButton)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.outputLabel = QtWidgets.QLabel(Dialog)
        self.outputLabel.setObjectName("outputLabel")
        self.verticalLayout_3.addWidget(self.outputLabel)
        self.outputListView = QtWidgets.QListView(Dialog)
        self.outputListView.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.outputListView.setObjectName("outputListView")
        self.verticalLayout_3.addWidget(self.outputListView)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.addFilesButton.setText(_translate("Dialog", "Add files"))
        self.addFolderButton.setText(_translate("Dialog", "Add folder"))
        self.removeFromInputButton.setText(_translate("Dialog", "Remove"))
        self.addToOutputButton.setText(_translate("Dialog", "Add to output"))
        self.inputLabel.setText(_translate("Dialog", "Input files"))
        self.sameSettingsCheckBox.setText(_translate("Dialog", "Same settings for all files"))
        self.channelsMappingLabel.setText(_translate("Dialog", "Channels mapping"))
        self.setOutputFolderButton.setText(_translate("Dialog", "Set folder"))
        self.convertButton.setText(_translate("Dialog", "Convert"))
        self.removeFromOutputButton.setText(_translate("Dialog", "Remove"))
        self.backToInputButton.setText(_translate("Dialog", "Back to input"))
        self.outputLabel.setText(_translate("Dialog", "Output queue"))

