# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'view.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1238, 768)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.addFilesButton = QtWidgets.QPushButton(Dialog)
        self.addFilesButton.setObjectName("addFilesButton")
        self.horizontalLayout_3.addWidget(self.addFilesButton)
        self.addFolderButton = QtWidgets.QPushButton(Dialog)
        self.addFolderButton.setObjectName("addFolderButton")
        self.horizontalLayout_3.addWidget(self.addFolderButton)
        self.removeFromInputButton = QtWidgets.QPushButton(Dialog)
        self.removeFromInputButton.setObjectName("removeFromInputButton")
        self.horizontalLayout_3.addWidget(self.removeFromInputButton)
        self.addToOutputButton = QtWidgets.QPushButton(Dialog)
        self.addToOutputButton.setObjectName("addToOutputButton")
        self.horizontalLayout_3.addWidget(self.addToOutputButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.inputLabel = QtWidgets.QLabel(Dialog)
        self.inputLabel.setObjectName("inputLabel")
        self.horizontalLayout.addWidget(self.inputLabel)
        self.inputStateLabel = QtWidgets.QLabel(Dialog)
        self.inputStateLabel.setObjectName("inputStateLabel")
        self.horizontalLayout.addWidget(self.inputStateLabel)
        self.inputProgressLabel = QtWidgets.QLabel(Dialog)
        self.inputProgressLabel.setEnabled(True)
        self.inputProgressLabel.setObjectName("inputProgressLabel")
        self.horizontalLayout.addWidget(self.inputProgressLabel)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.inputFilterEdit = QtWidgets.QLineEdit(Dialog)
        self.inputFilterEdit.setObjectName("inputFilterEdit")
        self.verticalLayout.addWidget(self.inputFilterEdit)
        self.inputListView = QtWidgets.QListView(Dialog)
        self.inputListView.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.inputListView.setObjectName("inputListView")
        self.verticalLayout.addWidget(self.inputListView)
        self.horizontalLayout_5.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.channelsMappingLabel = QtWidgets.QLabel(Dialog)
        self.channelsMappingLabel.setObjectName("channelsMappingLabel")
        self.verticalLayout_2.addWidget(self.channelsMappingLabel)
        self.channelsTreeView = QtWidgets.QTreeView(Dialog)
        self.channelsTreeView.setMinimumSize(QtCore.QSize(550, 0))
        self.channelsTreeView.setObjectName("channelsTreeView")
        self.verticalLayout_2.addWidget(self.channelsTreeView)
        self.horizontalLayout_5.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.setOutputFolderButton = QtWidgets.QPushButton(Dialog)
        self.setOutputFolderButton.setObjectName("setOutputFolderButton")
        self.horizontalLayout_2.addWidget(self.setOutputFolderButton)
        self.convertButton = QtWidgets.QPushButton(Dialog)
        self.convertButton.setObjectName("convertButton")
        self.horizontalLayout_2.addWidget(self.convertButton)
        self.removeFromOutputButton = QtWidgets.QPushButton(Dialog)
        self.removeFromOutputButton.setObjectName("removeFromOutputButton")
        self.horizontalLayout_2.addWidget(self.removeFromOutputButton)
        self.backToInputButton = QtWidgets.QPushButton(Dialog)
        self.backToInputButton.setObjectName("backToInputButton")
        self.horizontalLayout_2.addWidget(self.backToInputButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.outputLabel = QtWidgets.QLabel(Dialog)
        self.outputLabel.setObjectName("outputLabel")
        self.horizontalLayout_4.addWidget(self.outputLabel)
        self.outputStateLabel = QtWidgets.QLabel(Dialog)
        self.outputStateLabel.setObjectName("outputStateLabel")
        self.horizontalLayout_4.addWidget(self.outputStateLabel)
        self.outputProgressLabel = QtWidgets.QLabel(Dialog)
        self.outputProgressLabel.setObjectName("outputProgressLabel")
        self.horizontalLayout_4.addWidget(self.outputProgressLabel)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_4)
        self.outputListView = QtWidgets.QListView(Dialog)
        self.outputListView.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.outputListView.setObjectName("outputListView")
        self.verticalLayout_3.addWidget(self.outputListView)
        self.horizontalLayout_5.addLayout(self.verticalLayout_3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.addFilesButton.setText(_translate("Dialog", "Add files"))
        self.addFolderButton.setText(_translate("Dialog", "Add folder"))
        self.removeFromInputButton.setText(_translate("Dialog", "Remove"))
        self.addToOutputButton.setText(_translate("Dialog", "Add to output"))
        self.inputLabel.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Input files:</span></p></body></html>"))
        self.inputStateLabel.setText(_translate("Dialog", "Idle"))
        self.inputProgressLabel.setText(_translate("Dialog", "TextLabel"))
        self.channelsMappingLabel.setText(_translate("Dialog", "Channels mapping"))
        self.setOutputFolderButton.setText(_translate("Dialog", "Set folder"))
        self.convertButton.setText(_translate("Dialog", "Convert"))
        self.removeFromOutputButton.setText(_translate("Dialog", "Remove"))
        self.backToInputButton.setText(_translate("Dialog", "Back to input"))
        self.outputLabel.setText(_translate("Dialog", "<html><head/><body><p><span style=\" font-weight:600;\">Output queue:</span></p></body></html>"))
        self.outputStateLabel.setText(_translate("Dialog", "Idle"))
        self.outputProgressLabel.setText(_translate("Dialog", "TextLabel"))

