# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\view.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1024, 768)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.addFilesButton = QtWidgets.QPushButton(Dialog)
        self.addFilesButton.setObjectName("addFilesButton")
        self.horizontalLayout.addWidget(self.addFilesButton)
        self.addFolderButton = QtWidgets.QPushButton(Dialog)
        self.addFolderButton.setObjectName("addFolderButton")
        self.horizontalLayout.addWidget(self.addFolderButton)
        self.removeFromInputButton = QtWidgets.QPushButton(Dialog)
        self.removeFromInputButton.setObjectName("removeFromInputButton")
        self.horizontalLayout.addWidget(self.removeFromInputButton)
        self.addToOutputQueueButton = QtWidgets.QPushButton(Dialog)
        self.addToOutputQueueButton.setObjectName("addToOutputQueueButton")
        self.horizontalLayout.addWidget(self.addToOutputQueueButton)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.inputLabel = QtWidgets.QLabel(Dialog)
        self.inputLabel.setObjectName("inputLabel")
        self.verticalLayout.addWidget(self.inputLabel)
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setMaximumSize(QtCore.QSize(16777215, 22))
        self.textEdit.setObjectName("textEdit")
        self.verticalLayout.addWidget(self.textEdit)
        self.inputTreeView = QtWidgets.QTreeView(Dialog)
        self.inputTreeView.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.inputTreeView.setObjectName("inputTreeView")
        self.verticalLayout.addWidget(self.inputTreeView)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.sameSettingsCheckBox = QtWidgets.QCheckBox(Dialog)
        self.sameSettingsCheckBox.setObjectName("sameSettingsCheckBox")
        self.horizontalLayout_2.addWidget(self.sameSettingsCheckBox)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.channelsMappingLabel = QtWidgets.QLabel(Dialog)
        self.channelsMappingLabel.setObjectName("channelsMappingLabel")
        self.verticalLayout_2.addWidget(self.channelsMappingLabel)
        self.channelsTreeView = QtWidgets.QTreeView(Dialog)
        self.channelsTreeView.setObjectName("channelsTreeView")
        self.verticalLayout_2.addWidget(self.channelsTreeView)
        self.horizontalLayout_4.addLayout(self.verticalLayout_2)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.setOutputFolderButton = QtWidgets.QPushButton(Dialog)
        self.setOutputFolderButton.setObjectName("setOutputFolderButton")
        self.horizontalLayout_3.addWidget(self.setOutputFolderButton)
        self.convertButton = QtWidgets.QPushButton(Dialog)
        self.convertButton.setObjectName("convertButton")
        self.horizontalLayout_3.addWidget(self.convertButton)
        self.removeFromOutputButton = QtWidgets.QPushButton(Dialog)
        self.removeFromOutputButton.setObjectName("removeFromOutputButton")
        self.horizontalLayout_3.addWidget(self.removeFromOutputButton)
        self.backToInputButton = QtWidgets.QPushButton(Dialog)
        self.backToInputButton.setObjectName("backToInputButton")
        self.horizontalLayout_3.addWidget(self.backToInputButton)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem2)
        self.verticalLayout_3.addLayout(self.horizontalLayout_3)
        self.outputLabel = QtWidgets.QLabel(Dialog)
        self.outputLabel.setObjectName("outputLabel")
        self.verticalLayout_3.addWidget(self.outputLabel)
        self.outputTreeView = QtWidgets.QTreeView(Dialog)
        self.outputTreeView.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.outputTreeView.setObjectName("outputTreeView")
        self.verticalLayout_3.addWidget(self.outputTreeView)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.addFilesButton.setText(_translate("Dialog", "Add files"))
        self.addFolderButton.setText(_translate("Dialog", "Add folder"))
        self.removeFromInputButton.setText(_translate("Dialog", "Remove"))
        self.addToOutputQueueButton.setText(_translate("Dialog", "Add to output"))
        self.inputLabel.setText(_translate("Dialog", "Input files"))
        self.textEdit.setPlaceholderText(_translate("Dialog", "Name as filter"))
        self.sameSettingsCheckBox.setText(_translate("Dialog", "Same settings for all files"))
        self.channelsMappingLabel.setText(_translate("Dialog", "Channels mapping"))
        self.setOutputFolderButton.setText(_translate("Dialog", "Set folder"))
        self.convertButton.setText(_translate("Dialog", "Convert"))
        self.removeFromOutputButton.setText(_translate("Dialog", "Remove"))
        self.backToInputButton.setText(_translate("Dialog", "Back to input"))
        self.outputLabel.setText(_translate("Dialog", "Output queue"))
